terraform {
  required_version = ">= 1.6"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  # Remote state in S3. Concrete settings (bucket/key/region) live in
  # infra/backend.hcl, generated by scripts/create-s3.sh, so the account-scoped
  # bucket name isn't hard-coded here:
  #   tofu init -backend-config=backend.hcl
  backend "s3" {}
}

provider "aws" {
  region = var.aws_region
}

data "aws_caller_identity" "current" {}
